baseURL = "https://SimpleHarmonicMotion07.github.io/"
languageCode = "en-us"
title = "SimpleHarmonicMotion"
theme = "PaperMod"
publishDir = "docs"
relativeURLs = false
canonifyURLs = true

[params]
  author = "SimpleHarmonicMotion"
  description = "My Blog"
  defaultTheme = "auto"
  ShowPostList = true

[params.homeInfoParams]
  title = "Welcome!"
  content = "Hyunmin's portfolio"
  displaySocialIcons = true

[params.profileMode]
  enabled = true
  title = "SimpleHarmonicMotion"
  subtitle = "Hello, World!"
  imageUrl = "images/profile.png"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "profile image"

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 1

[[menu.main]]
  name = "Archive"
  url = "/archives"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 3

[[menu.main]]
  name = "About Me"
  url = "/about"
  weight = 4

[[menu.main]]
  name = "Profile"
  url = "/profile"
  weight = 5

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/SimpleHarmonicMotion07"

[[params.socialIcons]]
  name = "email"
  url = "hmshin070209@email.com"

[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/_simple_harmonic_motion/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.assets]
  disableFingerprinting = true