baseURL = "https://SimpleHarmonicMotion07.github.io/"
languageCode = "en-us"
title = "SimpleHarmonicMotion"
theme = "PaperMod"
publishDir = "docs"
relativeURLs = false
canonifyURLs = true

[params]
  author = "SimpleHarmonicMotion"
  description = "My Blog"
  defaultTheme = "auto"
  ShowPostList = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
