baseURL = "https://SimpleHarmonicMotion07.github.io/"
languageCode = "en-us"
title = "SimpleHarmonicMotion"
theme = "PaperMod"
publishDir = "docs"
relativeURLs = false
canonifyURLs = true

[params]
  author = "SimpleHarmonicMotion"
  description = "My Blog"
  defaultTheme = "auto"
  ShowPostList = true
  ShowTags = true
  customCSS = ["css/extra.css"]


[params.homeInfoParams]
  title = "Welcome!"
  content = "Hyunmin's portfolio"
  displaySocialIcons = true

[params.profileMode]
  enabled = true
  title = "SimpleHarmonicMotion"
  subtitle = "다이어트를 해야하지만 배가고파요 흐흑"
  imageUrl = "images/profile.png"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "profile image"
  buttons = [
    { name = "#RGS", url = "", class = "btn-RGS" },
    { name = "#StarButterfly", url = "https://starvstheforcesofevil.fandom.com/wiki/Star_Butterfly", class = "btn-StarButterfly" },
    { name = "#Lulu", url = "https://www.leagueoflegends.com/en-us/champions/lulu/", class = "btn-Lulu"},
    { name = "#Minecraft", url = "https://www.minecraft.net/ko-kr", class = "btn-Minecraft"},
  ]

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 1

[[menu.main]]
  name = "Archive"
  url = "/archives"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 3

[[menu.main]]
  name = "About Me"
  url = "/about"
  weight = 4

[[params.socialIcons]]
  name = "github"
  title = "SimpleHarmonicMotion07"
  url = "https://github.com/SimpleHarmonicMotion07"

[[params.socialIcons]]
  name = "email"
  title = "hmshin070209@gmail.com"
  url = "/addresses"

[[params.socialIcons]]
  name = "instagram"
  title = "@_simple_harmonic_motion"
  url = "https://www.instagram.com/_simple_harmonic_motion/"

[[params.socialIcons]]
  name = "discord"
  title =  "@SimpleHarmonicMotion07"
  url = "/addresses"


[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.assets]
  disableFingerprinting = true