baseURL = "https://SimpleHarmonicMotion07.github.io/"
languageCode = "en-us"
title = "SimpleHarmonicMotion"
theme = "PaperMod"

[params]
  author = "SimpleHarmonicMotion"
  description = "My Blog"
  defaultTheme = "auto"

[outputs]
  home = ["HTML", "RSS", "JSON"]
