baseURL = "https://SimpleHarmonicMotion07.github.io/"
languageCode = "en-us"
title = "SimpleHarmonicMotion"
theme = "PaperMod"
publishDir = "docs"
relativeURLs = false
canonifyURLs = true

[params]
  author = "SimpleHarmonicMotion"
  description = "My Blog"
  defaultTheme = "auto"
  ShowPostList = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params.assets]
  disableFingerprinting = true

[[params.socialIcons]]
name = "github"
url = "https://github.com/SimpleHarmonicMotion07"

[[params.socialIcons]]
name = "email"
url = "hmshin070209@email.com"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/_simple_harmonic_motion/"